---
title: "Data"
author: "Qi Wang"
date: "4/21/2017"
output: pdf_document
---

```{r}
library(dplyr)

data = read.csv('~/Documents/Duke/17Spring/STA644/GTD_0616dist/globalterrorismdb_0616dist.csv', header = T)
regions = data[,c('region','region_txt')]
reg_uniq = unique(regions) 
reg_uniq = reg_uniq[order(reg_uniq$region),]
n = nrow(reg_uniq)

for (i in 1:n){
  var = paste0("data",i,"_count")
  assign(var, data %>% filter(region == i) %>% group_by(iyear) %>% summarise(count = n()))
}

par(mfrow = c(3,4))
for(i in 1:n){
  plot(get(paste0("data",i,"_count")), type = 'l', main = reg_uniq[i,'region_txt'])
}


```
```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
library(ggplot2)
library(modelr)
library(tidyr)

for(i in 1:12){
  data_in_use = get(paste0("data",i,"_count"))
  l = lm(count~iyear, data = data_in_use)
  l2 = lm(count ~ iyear + I(iyear^2), data=data_in_use)
  
  d = data_in_use %>%
    add_predictions(l, var="l") %>%
    add_predictions(l2, var="l2")
  
  var = paste0("p",i)
  assign(var,ggplot(data_in_use, aes(x=iyear, y=count)) + 
           geom_line() + 
           geom_point() +
           geom_line(data=d, aes(x=iyear, y=l), color="red", size=1.2) +
           geom_line(data=d, aes(x=iyear, y=l2), color="blue", size=1.2)+
           ggtitle(reg_uniq[i,'region_txt']))
  
  d = data_in_use %>%
    add_residuals(l, var="resid_l") %>%
    add_residuals(l2, var="resid_q")
  
  var = paste0("r",i)
  
  assign(var,ggplot(gather(d, type, residual, -(iyear:count)), aes(x=iyear, y=residual, color=type)) + 
           geom_point() +
           geom_line() +
           facet_wrap(~type, nrow=2)+
           ggtitle(reg_uniq[i,'region_txt']))
}
multiplot(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12, cols = 4)
multiplot(r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12, cols = 4)


```



```{r}
par(mfrow = c(3,4))

for(i in 1:n){
  var = paste0("diff",i)
  data_c = get(paste0("data",i,"_count"))
  assign(var, diff(data_c$count))
  data_diff = get(paste0("diff",i))
  plot(data_diff,main = reg_uniq[i,'region_txt'])

}

for(i in 1:n){
  data_diff = get(paste0("diff",i))
  acf(data_diff,main = reg_uniq[i,'region_txt'])
}

for(i in 1:n){
  data_diff = get(paste0("diff",i))
  pacf(data_diff,main = reg_uniq[i,'region_txt'])
}
```
```{r}
library(forecast)
# par(mfrow=c(2,2))
# # acf(pmts,100)
# acf(diff(diff(pmts)),100)
# pacf(diff(diff(pmts)),100)
par(mfrow = c(3,4))
for(i in 1:n){
  data_diff = get(paste0("diff",i))
  var = paste0("perio",i)
  assign(var,spec.pgram(data_diff,taper=0,log="no",main="Raw Periodogram"))
}

```

```{r}

par(mfrow = c(3,4))

# North America
testarma=Arima(data1_count$count,order=c(1,1,1),seasonal=list(order=c(0,0,1),period=6))
testarma_res1 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[1,'region_txt'])


testarma=Arima(data2_count$count,order=c(0,1,1),seasonal=list(order=c(1,0,1),period=2))
testarma_res2 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[2,'region_txt'])

testarma=Arima(data3_count$count,order=c(5,1,1),seasonal=list(order=c(2,0,1),period=4))
testarma_res3 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[3,'region_txt'])

testarma=Arima(data4_count$count,order=c(3,1,3))
testarma_res4 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[4,'region_txt'])

testarma=Arima(data5_count$count,order=c(1,1,1),seasonal=list(order=c(2,0,1),period=4))
testarma_res5 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[5,'region_txt'])

testarma=Arima(data6_count$count,order=c(0,1,2),seasonal=list(order=c(2,0,1),period=6))
testarma_res6 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[6,'region_txt'])

testarma=Arima(data7_count$count,order=c(1,1,1),seasonal=list(order=c(2,0,1),period=2))
testarma_res7 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[7,'region_txt'])

testarma=Arima(data8_count$count,order=c(5,2,3))
testarma_res8 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[8,'region_txt'])

testarma=Arima(data9_count$count,order=c(3,1,2),seasonal=list(order=c(0,0,1),period=2))
testarma_res9 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[9,'region_txt'])

testarma=Arima(data10_count$count,order=c(5,1,5),seasonal=list(order=c(3,0,1),period=4))
testarma_res10 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[10,'region_txt'])

testarma=Arima(data11_count$count,order=c(5,1,3),seasonal=list(order=c(2,0,1),period=2))
testarma_res11 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[11,'region_txt'])

testarma=Arima(data12_count$count,order=c(2,1,3))
testarma_res12 = testarma$residuals
pmdarmaforecast=forecast.Arima(testarma,h=5)
plot.forecast(pmdarmaforecast,main=reg_uniq[12,'region_txt'])


```

```{r}
par(mfrow=c(1,3), mar=c(2,4,6,2))
for (i in 1:n){
  testarma_res = get(paste0("testarma_res",i))
  plot(testarma_res,main=reg_uniq[i,'region_txt'])
  acf(testarma_res)
  pacf(testarma_res)
}
```


